# Code Generated by Sidekick is for learning and experimentation purposes only.

from datetime import datetime, timedelta

# ── FHIR API ──────────────────────────────────────────────────────────────────
FHIR_BASE_URL   = "https://hapi.fhir.org/baseR4"
PAGE_COUNT      = 50          # _count per page
RESOURCES       = ["Patient", "Encounter", "Observation", "Condition"]
RESPONSE_FORMAT = "json"      # switch to "xml" for optional extension

# ── Incremental window (2–3 days) ─────────────────────────────────────────────
DAYS_BACK   = 3
START_DATE  = (datetime.utcnow() - timedelta(days=DAYS_BACK)).strftime("%Y-%m-%d")
END_DATE    = datetime.utcnow().strftime("%Y-%m-%d")

# ── Lakehouse paths (Microsoft Fabric) ────────────────────────────────────────
# Replace with your Fabric lakehouse mount path or ABFS path
LAKEHOUSE_ROOT = "Files"       # relative path in Fabric notebook
RAW_PATH       = f"{LAKEHOUSE_ROOT}/raw"
BRONZE_PATH    = f"{LAKEHOUSE_ROOT}/bronze"
SILVER_PATH    = f"{LAKEHOUSE_ROOT}/silver"
GOLD_PATH      = f"{LAKEHOUSE_ROOT}/gold"

# ── Delta table names (registered in Lakehouse) ───────────────────────────────
BRONZE_DB = "bronze"
SILVER_DB = "silver"
GOLD_DB   = "gold"
